// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bflcbfznujnffaixeqby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmbGNiZnpudWpuZmZhaXhlcWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NzM0ODMsImV4cCI6MjA1NjQ0OTQ4M30.7MF9N-UGT4cktY-x_HkZJN_Z6fk_g4Vw_rSlnTvXHRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);